# Generated by Django 2.2 on 2024-01-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20240124_0259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
